---
#
# MQTT virtual sensor from smartthings
#
platform: mqtt
name: "Freezer Sensor temp"
unique_id: "Freezer Sensor Temp"
state_topic: "smartthings/Freezer Sensor/temperature/state"
device_class: "temperature"
unit_of_measurement: "°F"