---
#
# MQTT virtual sensor from smartthings
#
platform: mqtt
name: "Living Room Motion Sensor battery"
unique_id: "Living Room Motion Sensor battery"
state_topic: "smartthings/Living Room Motion Sensor/battery/state"
device_class: "battery"
unit_of_measurement: "%"