---
#
# MQTT virtual sensor from smartthings
#
platform: mqtt
name: "Master Bedroom Closet Motion Sensor battery"
unique_id: "Master Bedroom Closet Motion Sensor Battery"
state_topic: "smartthings/Master Bedroom Closet Motion Sensor/battery/state"
device_class: "battery"
unit_of_measurement: "%"