---
#
# The Home Assistant Cloud allows you to quickly
# integrate your local Home Assistant with various
# cloud services like Amazon Alexa and Google Assistant.
#
# https://www.home-assistant.io/components/cloud/
#
cloud:

