---
#
# The Home Assistant Cloud allows you to quickly
# integrate your local Home Assistant with various
# cloud services like Amazon Alexa and Google Assistant.
#
# https://www.home-assistant.io/components/cloud/
#
cloud:
  alexa:
    filter:
      include_entities:
        - automation.weather_report
#      include_domains:
      exclude_entities:
        - light.kohree2
        - light.kohree_1
        - light.sengled_e11_g13_030ba25e_1
        - light.sengled_e11_g13_030ba3b9_1
        - light.sengled_e11_g13_030bbabf_1
        - light.sengled_e11_g13_030bbd4e_1
        - switch.ha_dockermon_chaotics_minecraft_server
        - switch.ha_dockermon_docker_influxdb_grafana
        - switch.ha_dockermon_duckdns
        - switch.ha_dockermon_ha_dockermon
        - switch.ha_dockermon_home_assistant
        - switch.ha_dockermon_jackett
        - switch.ha_dockermon_letsencrypt
        - switch.ha_dockermon_mariadb
        - switch.ha_dockermon_mqtt
        - switch.ha_dockermon_mqtt_internal
        - switch.ha_dockermon_nextcloud
        - switch.ha_dockermon_ombi
        - switch.ha_dockermon_plex
        - switch.ha_dockermon_qbittorrent
        - switch.ha_dockermon_radarr
        - switch.ha_dockermon_smartthings_mqtt_bridge
        - switch.ha_dockermon_sonarr
        - switch.ha_dockermon_tasmoadmin
        - switch.ha_dockermon_tautulli
        - switch.ha_dockermon_transmission
        - group.all_automations
        - group.all_switches
        - group.calendar
        - group.device_trackers
        - script.sonos_say
        - media_player.adult_sonos
        - media_player.livingroom_sonos
        - media_player.kids_bedroom
      exclude_domains:
        - sensor
        - binary_sensor
        - automation
    entity_config:
      group.living_room:
        name: Living Room
        description: The light in the Living Room
      group.master_bedroom_closet:
        name: Master Bedroom Closet
        description: The light in the Master Bedroom Closet
      switch.gosund_1:
        display_categories: LIGHT
        name: Kedar's Night Light
        description: Kedar's Night Light
      switch.gosund_2:
        display_categories: LIGHT
        name: Matt's Night Light
        description: Matt's Night Light
