---
#
# Custom component to track other custom components
#
# https://github.com/custom-components/custom_updater
#
custom_updater:
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
  show_installable: true
  track:
    - cards
    - components
    - pythons_scripts