---
#
# Custom component to track other custom components
#
# https://github.com/custom-components/custom_updater
#
custom_updater:
  track:
    - cards
    - components
    - pythons_scripts
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json