---
# The http component serves all files and data required for the
# Home Assistant frontend.
#
# https://www.home-assistant.io/components/http/
#
http:
  # Protects Home Assistant with a password.
 # api_password: !secret http_password

  # Contains the URL that Home Assistant is available on the internet.
  #base_url: !secret http_base_url
  external_url: !secret http_base_url
  internal_url: !secret http_base_url

  # Enable parsing of the X-Forwarded-For header, passing on the client’s
  # correct IP address, since I'm using a proxied setup.
  use_x_forwarded_for: true

  # List of trusted proxies, consisting of IP addresses or networks,
  # that are allowed to set the X-Forwarded-For header.
  trusted_proxies: !secret http_trusted_proxies

  # Enables additional IP filtering.
  ip_ban_enabled: true

  # Number of failed login attempts from a single IP after which it will
  # be automatically banned.
  login_attempts_threshold: 5