---
# Connects to my MQTT broker, for which I use the Community add-on:
# "MQTT Server & Web Client".
#
# https://github.com/hassio-addons/addon-mqtt/blob/master/README.md
# https://www.home-assistant.io/docs/mqtt/broker#run-your-own
# https://www.home-assistant.io/docs/mqtt/birth_will/
#
mqtt:
  broker: !secret server_ip
  port: 1883
  birth_message:
    topic: 'homeassistant/status'
    payload: 'online'
  will_message:
    topic: 'homeassistant/status'
    payload: 'offline'