---
#
# The person component allows to connect device tracker
# entities to one or more person entities. The last state
# update of a connected device tracker will set the state
# of the person. For example if you connect your router and
# your OwnTracks device as trackers to your person, the
# last state update from either the router or your OwnTracks
# device will set the state of your person.
#
# https://www.home-assistant.io/components/person
#
person: