---
# The transmission platform allows you to monitor your downloads with Transmission
# from within Home Assistant and setup automation based on the information.
#
# https://www.home-assistant.io/components/transmission/
#
transmission:
  host: !secret server_ip
  username: !secret transmission_user
  password: !secret transmission_password
  monitored_conditions:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'
    - 'active_torrents'
    - 'paused_torrents'
    - 'total_torrents'