---
# The updater component will check daily for new releases.
# It will show a badge in the frontend if a new version is found.
#
# https://www.home-assistant.io/components/updater/
#
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
#
updater:
  # Share info with the developers
  reporting: true

  # I'm also reporting a list of components that I'm using.
  include_used_components: true