---
# The tomato platform requires an extra config variable called http_id.
# The value can be obtained by logging in to the Tomato admin interface
# and search for http_id in the page source code.
#
# https://www.home-assistant.io/components/device_tracker.tomato/
#
platform: tomato
host: !secret tomato_ip
username: !secret tomato_user
password: !secret tomato_password
http_id: !secret tomato_http_id
new_device_defaults:
  track_new_devices: false