---
#
# The iss platform uses the Open Notify API to let you know if the station is
# above your home location. This means that ISS is 10° above the horizon of your home.
#
# https://www.home-assistant.io/components/binary_sensor.iss/
#
platform: iss