homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  
  # Pick yours from here:
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: EST
  
  # Load packages
  packages: !include_dir_named components/packages

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
 http:
   base_url: chaoticunreal.duckdns.org:8123
   api_password: !secret http_password
# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun: