---
#
# restart mqtt internal
#
id: check mqtt internal
alias: check mqtt internal
initial_state: 'on'
trigger:
  - platform: state
    entity_id: switch.ha_dockermon_mqtt_internal
    to: 'off'
    for:
      minutes: 5
action:
  - service: homeassistant.turn_on
    entity_id:       
    - switch.ha_dockermon_mqtt_internal
  - service: persistent_notification.create
    data_template:
      notification_id: offline_container
      title: Container Offline
      message: >
        Docker container for {{ trigger.to_state.name }} is not running. Please check the status of this container as some features may stop functioning.
