---
# This is an input select to use with waze
# To Select travel time.
#
# https://www.home-assistant.io/components/input_select/
#
destination:
    name: destination
    options:
      - Home
      - Work
      - Dads
      - Nana & Grampy