---
#
# MQTT virtual sensor from smartthings
#
platform: mqtt
name: "Freezer Sensor"
unique_id: "Freezer Sensor Contact"
state_topic: "smartthings/Freezer Sensor/contact/state"
payload_on: "open"
payload_off: "closed"
device_class: "door"