---
# 
# Climacell Weather Platform
#
# https://github.com/r-renato/ha-climacell-weather
#
platform: climacell
api_key: !secret climacell_api_key
name: climacell
latitude: !secret latitude
longitude: !secret longitude
units: metric
timelines:
  - name: "Daily"
    fields:
      - temperature
      - wind_direction
      - precipitation
      - precipitation_type
      - wind_speed
      - wind_direction
      - weather_condition
      - pollen_tree
      - pollen_weed
      - pollen_grass
    start_time: -5
    forecast_observations: 3
    timestep: "1d"
    update: auto
    scan_interval:
      # At least one of these must be specified:
      days: 0
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
    exclude_interval:
      1:
        - "09:00"
        - "10:00"
      2:
        - "13:00"
        - "14:00"
      3:
        - "18:00"
        - "07:00"