---
#
# The Fitbit sensor allows you to expose data from Fitbit to Home Assistant.
#
# https://www.home-assistant.io/components/sensor.fitbit/
#
platform: fitbit
clock_format: 24H
unit_system: en_US
monitored_resources:
  - activities/activityCalories
  - activities/calories
  - activities/caloriesBMR
  - activities/distance
  - activities/elevation
  - activities/floors
  - activities/heart
  - activities/minutesFairlyActive
  - activities/minutesLightlyActive
  - activities/minutesSedentary
  - activities/minutesVeryActive
  - activities/steps
  - devices/battery
  - sleep/awakeningsCount
  - sleep/efficiency
  - sleep/minutesAfterWakeup
  - sleep/minutesAsleep
  - sleep/minutesAwake
  - sleep/minutesToFallAsleep
  - sleep/startTime
  - sleep/timeInBed