---
#
# The flunearyou sensor platform allows users in the United States and its
# territories to get information regarding reported flu symptoms from Flu Near You. 
#
# Defaults to the lat/long defined in the main HA config
#
# https://www.home-assistant.io/components/sensor.flunearyou/
#
platform: flunearyou
