---
#
# MQTT virtual sensor from smartthings
#
platform: mqtt
name: "Freezer Sensor"
unique_id: "Freezer Sensor Battery"
state_topic: "smartthings/Freezer Sensor/battery/state"
device_class: "battery"
device: "Freezer Sensor"