---
# The waze_travel_time sensor provides travel time from the Waze.
#
# https://www.home-assistant.io/components/sensor.waze_travel_time/
#
platform: waze_travel_time
name: "Me to destination"
origin: device_tracker.owntracks_matt
destination: sensor.dest_address
region: 'US'