---
#
# Code to turn off the master bedroom closet lights when there is no motion
#
id: Closet Light off
alias: Turn off closet light when there is movement
initial_state: 'on'
trigger:
  platform: state
  entity_id: binary_sensor.master_bedroom_closet_motion_sensor
  to: 'off'
  for:
    minutes: 5
action:
  service: homeassistant.turn_off
  entity_id:       
    - light.sengled_e11_g13_030ba25e_1
    - light.sengled_e11_g13_030bbabf_1
