---
#
# Code to turn on the closet lights when there is motion
#
id: Closet light On day
alias: Turn on closet light when there is movement day
initial_state: 'on'
trigger:
  platform: state
  entity_id: binary_sensor.master_bedroom_closet_motion_sensor
  to: 'on'
condition:
  - condition: time
    after: '05:30'
    before: '23:00'
action:
  service: light.turn_on
  data:
    brightness: 255
    entity_id:
      - light.sengled_e11_g13_030ba25e_1
      - light.sengled_e11_g13_030bbabf_1
