---
#
# shut everything off when everyone leaves
#
id: Shut it all off
alias: All off when everyone leaves
initial_state: 'on'
trigger:
  - entity_id: group.device_trackers
    platform: state
    to: not_home
    for: "00:10:00"
condition:
  - condition: state
    entity_id: 'input_boolean.guest_mode'
    state: 'off'
action:
  - service: homeassistant.turn_off
    entity_id: group.all_lights_custom