---
#
# Fade in the kids bedroom lights over 5 mins
#
id: Kids morning Wake Up
alias: Kids Bedroom Light Fade In
initial_state: 'on'
trigger:
  - platform: time
    at: "07:25:00"
condition:
  - condition: state
    entity_id: 'binary_sensor.workday'
    state: 'on'
  - condition: state
    entity_id: 'input_boolean.vacation'
    state: 'off'
  - condition: state
    entity_id: 'input_boolean.kids_vacation'
    state: 'off'
  - condition: state
    entity_id: 'input_boolean.snow_day'
    state: 'off'
action:
  - service: python_script.fade_in_light_2
    data:
      entity_id: light.kids_bedroom
      brightness_pct: 100
      transition: 300