---
#
# Kids "clock" light green
#
id: Kids Clock Light Green
alias: Kids clock light green
initial_state: 'on'
trigger:
  - platform: time
    at: "07:00:00"
condition:
  - condition: state
    entity_id: 'input_boolean.kids_vacation'
    state: 'off'
action:
  - service: light.turn_on
    data:
      entity_id: light.kids_night_light
      color_name: green
      brightness_pct: 100