---
#
# Code to turn on the living room lights when there is motion
#
id: Kids Room Vacation
alias: Turn on Kids room light when Vacation
initial_state: 'on'
trigger:
  - platform: time
    at: "21:00:00"
condition:
  - condition: state
    entity_id: 'input_boolean.vacation'
    state: 'on'
action:
  service: light.turn_on
  entity_id: light.kids_bedroom