---
#
# shut the kids clock light
#
id: Kids off for school
alias: Kids off for school
initial_state: 'on'
trigger:
  - platform: time
    at: "09:00:00"
action:
  - service: homeassistant.turn_off
    entity_id: light.kohree_4