---
#
# Kids "clock" light red
#
id: Kids Clock Light Red
alias: Kids clock light red
initial_state: 'on'
trigger:
  - platform: time
    at: "19:30:00"
condition:
  - condition: state
    entity_id: 'input_boolean.kids_vacation'
    state: 'off'
action:
  - service: light.turn_off
    entity_id: light.kohree_4
    color_name: red
    brightness_pct: 20