---
#
# Code to turn on the living room lights when there is motion
#
id: Living Room Off day
alias: Turn on living room light when there is movement day
initial_state: 'on'
trigger:
  platform: state
  entity_id: binary_sensor.bosch_isw_zpr1_wp13_b44cc34b_5_1280
  to: 'on'
condition:
  - condition: template
    value_template: "{{ not is_state('media_player.living_room_tv', 'playing') }}"
  - condition: state
    entity_id: 'input_boolean.movie_mode'
    state: 'off'
  - condition: time
    after: '05:30'
    before: '23:00'
action:
  service: light.turn_on
  data:
    brightness: 255
    color_temp: 243
    entity_id:
      - light.kohree2
      - light.kohree_1
