---
#
# Code to turn off the living room lights when there is no motion
#
id: Shut if all off night
alias: Turn off living room light when there is no movement night
initial_state: 'on'
trigger:
  platform: state
  entity_id: binary_sensor.bosch_isw_zpr1_wp13_b44cc34b_5_1280
  to: 'off'
  for:
    minutes: 3
condition:
  condition: or
  conditions:
    - condition: time 
      after: "23:00:00" #11pm - midnight 
    - condition: time 
      before: "05:30:00" #midnight - 5:30am
action:
  service: light.turn_off
  data:
    entity_id:
      - light.kohree2
      - light.kohree_1
