---
#
# Fade in the master bedroom lights over 30 mins
#
id: Master Bedroom Wake up
alias: Master Bedroom Light Fade In
initial_state: 'on'
trigger:
  - platform: time
    at: "05:50:00"
condition:
  - condition: state
    entity_id: 'binary_sensor.workday'
    state: 'on'
  - condition: state
    entity_id: 'input_boolean.vacation'
    state: 'off'
action:
  - service: python_script.fade_in_light_2
    data:
      entity_id: light.master_bedroom
      brightness_pct: 100
      transition: 600
