---
#
# Code to turn on the living room lights when there is motion
#
id: Master bedroom Vacation
alias: Turn on Master bedroom light when Vacation
initial_state: 'on'
trigger:
  - platform: time
    at: "21:45:00"
condition:
  - condition: state
    entity_id: 'input_boolean.vacation'
    state: 'on'
action:
  - delay: '{{ "00:" ~ ((range(0, 1) | random) | int)  ~ ":" ~  ((range(5, 55) | random) | int) }}'
  - service: light.turn_on
    entity_id: light.master_bedroom