---
#
# turn off outside lights at sunrise
#
id: Turn off Outside Lights at sunset
alias: Outside lights off at Sunset
initial_state: 'on'
trigger:
  platform: sun
  event: sunrise
  offset: '+00:45:00'
action:
  - service: homeassistant.turn_off
    entity_id: group.outside_lights