---
#
# Scene to shut off the overhead light and turn on the side night stand lights
#
name: Laying in Bed
entities:
  light.master_bedroom:
    state: off
  switch.kedar_night_light:
    state: on
  switch.matts_night_light:
    state: on