---
#
# Scene to shut off the overhead light and turn on the side night stand lights
#
name: Laying in Bed
entities:
  light.master_bedroom:
    state: off
  switch.gosund_1:
    state: on
  switch.master_bedroom_lamp:
    state: on