---
#
# Scene to shut off the overhead light and turn on the side night stand lights
#
name: Laying in Bed
entities:
  light.master_bedroom:
    state: off
  light.kedar_s_night_light:
    state: on
    color_name: white
    brightness_pct: 100
    color_temp: 500
  light.matt_s_night_light:
    state: on
    color_name: white
    brightness_pct: 100
    color_temp: 500