---
#
# Scene to dim the lights when watching movies
#
name: Movie Mode On
entities:
  light.sengled_e11_g13_030ba3b9_1:
    state: on
    brightness_pct: 35
  light.sengled_e11_g13_030bbd4e_1:
    state: on
    brightness_pct: 35
