---
#
# Scene to return the lights to normal
#
name: Movie Mode Off
entities:
  light.kohree_2:
    state: on
    brightness_pct: 100
    color_temp: 243
  light.kohree_1:
    state: on
    brightness_pct: 100
    color_temp: 243

