---
#
# Scene to return the lights to normal
#
name: Movie Mode Off
entities:
  light.sengled_e11_g13_030ba3b9_1:
    state: on
    brightness_pct: 100
  light.sengled_e11_g13_030bbd4e_1:
    state: on
    brightness_pct: 100

