---
#
# notify when a freezer is off
#
id: Freezer Off
alias: freezer off
initial_state: 'on'
trigger:
  - platform: state
    entity_id: 
      - switch.gosund_8
    from: 'on'
action:
- service: notify.pushbullet
  data_template:
    message: 'The Freezer is Down! '
