---
#
# shut everything off
#
alias: All off
trigger:
  - platform: time
    at: "23:00:00"
action:
  - service: homeassistant.turn_off
    entity_id: group.all_lights
action:
  - service: homeassistant.turn_off
    entity_id: group.all_switches