---
#
# shut everything off at night
#
id: Shut it all off to sleep
alias: All off at night
trigger:
  - platform: time
    at: "23:00:00"
action:
  - service: homeassistant.turn_off
    entity_id: group.all_lights_custom