---
#
# Code to turn off the master bedroom closet lights when there is no motion
#
id: Closet Light off
alias: Turn off closet light when there is movement
initial_state: 'on'
trigger:
  platform: state
  entity_id: binary_sensor.master_bedroom_closet_motion_sensor
  to: 'off'
  for:
    minutes: 3
condition:
  - condition: time
    after: '06:00'
    before: '23:00'
action:
  service: homeassistant.turn_off
  entity_id: light.master_bedroom_closet
