---
#
# Code to turn on the living room lights when there is motion
#
id: Closet light On
alias: Turn on closet light when there is movement
initial_state: 'on'
trigger:
  platform: state
  entity_id: binary_sensor.master_bedroom_closet_motion_sensor
  to: 'on'
action:
  service: homeassistant.turn_on
  entity_id:
    - light.sengled_e11_g13_030ba25e_1
    - light.sengled_e11_g13_030bbabf_1
