---
#
# Code to dim the living room lights when I start playing a video
#
alias: "Media player playing"
trigger:
  - platform: state
    entity_id: media_player.living_room_tv
    to: 'playing'
    from: 'off'
  - platform: state
    entity_id: media_player.living_room_tv
    to: 'playing'
    from: 'paused'
  - platform: state
    entity_id: media_player.living_room_tv
    to: 'playing'
    from: 'idle'
# No condition right now
#condition:
#  - condition: state
#    entity_id: sun.sun
#    state: 'below_horizon'
action:
  service: scene.turn_on
  entity_id: scene.movie_mode_on