---
#
# Code to dim the living room lights when I start playing a video
#
id: Wacth the Movies
alias: "Media player playing"
initial_state: 'off'
trigger:
  - platform: state
    entity_id: media_player.living_room_tv
    to: 'playing'
    from: 'off'
  - platform: state
    entity_id: media_player.living_room_tv
    to: 'playing'
    from: 'paused'
  - platform: state
    entity_id: media_player.living_room_tv
    to: 'playing'
    from: 'idle'
action:
  service: scene.turn_on
  entity_id: scene.movie_mode_on