---
#
# Fade in the kids bedroom lights over 15 mins
#
alias: Kids Bedroom Light Fade In
trigger:
  - platform: time
    at: "05:45:00"
condition:
  condition: state
  entity_id: 'binary_sensor.workday_sensor'
  state: 'on'
action:
  - service: python_script.fade_in_light
    data:
      entity_id: light.kids_bedroom
      delay_in_sec: 9
      start_level_pct: 5
      end_level_pct: 100
      step_in_level_pct: 1
