---
#
# Code to turn on the living room lights when there is motion
#
id: Living Room Off night
alias: Turn on living room light when there is movement night
initial_state: 'on'
trigger:
  platform: state
  entity_id: binary_sensor.living_room_motion_sensor
  to: 'on'
condition:
  - condition: template
    value_template: "{{ not is_state('media_player.living_room_tv', 'playing') }}"
  - condition: state
    entity_id: 'input_boolean.movie_mode'
    state: 'off'
  - condition:
    condition: or
    conditions:
      - condition: time 
        after: "23:00:00" #11pm - midnight 
      - condition: time 
        before: "05:30:00" #midnight - 5:30am
action:
  service: light.turn_on
  data:
    brightness: 50
    entity_id:
      - light.living_room
