---
#
# Code to turn on the living room lights when there is motion
#
alias: Turn on kitchen light when there is movement
trigger:
  platform: state
  entity_id: binary_sensor.living_room_motion_sensor
  to: 'on'
condition:
  - condition: state
    entity_id: media_player.living_room_tv
    state: playing
  - condition: time
    after: '06:00'
    before: '23:00'
action:
  service: homeassistant.turn_on
  entity_id: llight.living_room