---
#
# Code to turn off the living room lights when there is no motion
#
id: Shut if all off night
alias: Turn off living room light when there is no movement night
initial_state: 'on'
trigger:
  platform: state
  entity_id: binary_sensor.living_room_motion_sensor
  to: 'off'
  for:
    minutes: 3
condition:
  condition: or
  conditions:
    - condition: time 
      after: "23:00:00" #11pm - midnight 
    - condition: time 
      before: "05:30:00" #midnight - 5:30am
action:
  service: homeassistant.turn_off
  entity_id: light.living_room
