---
#
# Code to return the living room lights to normal after playing a video
#
id: The player Stopped
alias: "Media player paused/stopped"
initial_state: 'on'
trigger:
  - platform: state
    entity_id: media_player.living_room_tv
    from: 'playing'
    to: 'idle'
  - platform: state
    entity_id: media_player.living_room_tv
    from: 'playing'
    to: 'paused'
  - platform: state
    entity_id: media_player.living_room_tv
    from: 'playing'
    to: 'off'
condition:
  - condition: state
    entity_id: 'input_boolean.movie_mode'
    state: 'on'
action:
    service: scene.turn_on
    entity_id: scene.movie_mode_off