---
#
# test the sonos tts
#
id: sonos_test
alias: sonos_test
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_text.sonos_says
action:
- service: script.sonos_say
  data_template:
    sonos_entity: adult_sonos
    volume: 0.5
    message: "{{ states.input_text.sonos_says.state }}"