---
#
# Code to turn speak the weather in the living room in the morning.
#
id: Weather Report
alias: Weather Report
initial_state: 'on'
trigger:
  platform: state
  entity_id: binary_sensor.living_room_motion_sensor
  to: 'on'
condition:
  - condition: time
    after: '05:30'
    before: '08:00'
action:
- service: script.sonos_say
  data_template:
    sonos_entity: livingroom_sonos
    volume: 0.5
    message: >
      Good morning. It is currently {{states.sensor.dark_sky_summary.state}} and {{states.sensor.dark_sky_temperature.state|round}} degrees in Lowell. Today will be {{states.sensor.dark_sky_hourly_summary.state|replace(".", "")}}, with a high of {{states.sensor.dark_sky_daily_high_temperature_0.state|round}} degrees.