---
#
# The Configuration for me
#
# https://www.home-assistant.io/components/person
#
name: matt
id: matt1
user_id: !secret matt_id
device_trackers:
  - device_tracker.matt
  - device_tracker.owntracks_matt