---
#
# shut AC off when everyone leaves
#
id: Thermostat Shut ac off cause everyone left
alias: Thermostat AC off when everyone leaves
initial_state: 'off'
trigger:
  - entity_id: group.device_trackers
    platform: state
    to: not_home
    for: "00:10:00"
condition:
  - condition: state
    entity_id: 'input_boolean.guest_mode'
    state: 'off'
action:
  - service: climate.set_temperature
    data:
      entity_id: climate.radio_thermostat_company_of_america_ct101_thermostat_iris_mode
      target_temp_high: 80
      target_temp_low: 55