---
#
# Shut the heat off at night in the winter
#
id: Thermostat heat down at night
alias: Thermostat heat down at night
initial_state: 'on'
trigger:
  - platform: time
    at: "23:00:00"
action:
  - service: climate.set_temperature
    data:
      entity_id: climate.2gig_technologies_ct101_thermostat_iris_mode
      target_temp_low: 60