---
#
# Shut the AC off at night in the summer
#
id: Thermostat AC up at night
alias: Thermostat AC up at night
initial_state: 'off'
trigger:
  - platform: time
    at: "1:00:00"
action:
  - service: climate.set_temperature
    data:
      entity_id: climate.radio_thermostat_company_of_america_ct101_thermostat_iris_mode
      target_temp_high: 75
      target_temp_low: 55