---
#
# Shut the heat on the morning during the winter
#
id: Thermostat heat on in the morning workday
alias: Thermostat heat on in the morning workday
initial_state: 'on'
trigger:
  - platform: time
    at: "05:30:00"
condition:
  - condition: numeric_state
    entity_id: 'sensor.dark_sky_temperature_low_0d'
    above: 50
  - condition: state
    entity_id: 'binary_sensor.workday'
    state: 'on'
  - condition: state
    entity_id: 'input_boolean.vacation'
    state: 'off'
  - condition: state
    entity_id: group.device_trackers
    state: 'home'
action:
  - service: climate.set_temperature
    data:
      entity_id: climate.2gig_technologies_ct101_thermostat_iris_heating_1
      temperature: 65