---
#
# Shut the heat on the morning during the winter
#
id: Thermostat heat on in the morning nonworkday
alias: Thermostat heat on in the morning nonworkday
initial_state: 'off'
trigger:
  - platform: time
    at: "08:30:00"
condition:
  - condition: numeric_state
    entity_id: 'sensor.dark_sky_overnight_low_temperature_0d'
    below: 50
  - condition: state
    entity_id: 'binary_sensor.workday'
    state: 'off'
  - condition: state
    entity_id: 'input_boolean.vacation'
    state: 'off'
  - condition: state
    entity_id: group.device_trackers
    state: 'home'
action:
  - service: climate.set_temperature
    data:
      entity_id: climate.radio_thermostat_company_of_america_ct101_thermostat_iris_mode
      target_temp_low: 65
      target_temp_high: 85