---
#
# Shut the AC on the morning during the summer
#
id: Thermostat AC on in the morning workday
alias: Thermostat AC on in the morning workday
initial_state: 'on'
trigger:
  - platform: time
    at: "07:30:00"
condition:
  - condition: numeric_state
    entity_id: 'sensor.dark_sky_daytime_high_temperature_0d'
    above: 85
  - condition: state
    entity_id: 'binary_sensor.workday'
    state: 'on'
  - condition: state
    entity_id: 'input_boolean.vacation'
    state: 'off'
  - condition: state
    entity_id: group.device_trackers
    state: 'home'
action:
  - service: climate.set_temperature
    data:
      entity_id: climate.radio_thermostat_company_of_america_ct101_thermostat_iris_mode
      target_temp_high: 75
      target_temp_low: 55