---
#
# turn heat on when someone comes home
#
id: Thermostat turn heat on cause someone is home
alias: Thermostat Heat on cause someone is home
initial_state: 'on'
trigger:
  - entity_id: group.device_trackers
    platform: state
    to: home
    for: "00:02:00"
condition:
  - condition: numeric_state
    entity_id: 'sensor.dark_sky_overnight_low_temperature_0d'
    below: 50
action:
  - service: climate.set_temperature
    data:
      entity_id: climate.2gig_technologies_ct101_thermostat_iris_heating_1
      temperature: 65