---
#
# Shut the heat on the morning during the winter
#
id: Thermostat heat on in the morning nonworkday
alias: Thermostat heat on in the morning nonworkday
initial_state: 'on'
trigger:
  - platform: time
    at: "06:30:00"
condition:
  - condition: state
    entity_id: 'sensor.season'
    state: 'winter'
  - condition: state
    entity_id: 'binary_sensor.workday'
    state: 'off'
  - condition: state
    entity_id: 'input_boolean.vacation'
    state: 'off'
action:
  - service: climate.set_temperature
    data:
      entity_id: climate.2gig_technologies_ct101_thermostat_iris_heating_1
      temperature: 65