---
#
# Thermostat baseline
#
id: Thermostat baseline
alias: Thermostat baseline
initial_state: 'on'
trigger:
  - platform: time
    at: "23:00:00"
condition:
  - condition: numeric_state
    entity_id: 'sensor.dark_sky_daytime_high_temperature_0d'
    below: 85
  - condition: numeric_state
    entity_id: 'sensor.dark_sky_overnight_low_temperature_0d'
    above: 50
action:
  - service: climate.set_temperature
    data:
      entity_id: climate.radio_thermostat_company_of_america_ct101_thermostat_iris_mode
      target_temp_high: 80
      target_temp_low: 55