---
# This is an input boolean to use with automations
# for when the kids are on vacation.
#
# https://www.home-assistant.io/components/input_boolean/
#
kids vacation:
  name: Enables kids vacation Mode
  initial: false
  icon: mdi:beach