---
# This is an input boolean to use with automations
# For movie mode.
#
# https://www.home-assistant.io/components/input_boolean/
#
movie_mode:
  name: Enables movie Mode
  initial: false
  icon: mdi:filmstrip