---
#
# Zones allow you to specify certain regions on earth (for now). 
#
# https://www.home-assistant.io/components/zone
#
name: Chiropractor
latitude: !secret zone_chiropractor_latitude
longitude: !secret zone_chiropractor_longitude
radius: 100
passive: false
icon: mdi:doctor