---
#
# Zones allow you to specify certain regions on earth (for now). 
#
# https://www.home-assistant.io/components/zone
#
name: Erin's Work
latitude: !secret zone_erin_latitude
longitude: !secret zone_erin_longitude
radius: 100
passive: false
icon: mdi:domain