---
#
# Zones allow you to specify certain regions on earth (for now). 
#
# https://www.home-assistant.io/components/zone
#
name: Kedars Work
latitude: !secret zone_ktwork1_latitude
longitude: !secret zone_ktwork1_longitude
radius: 100
passive: false
icon: mdi:domain