---
#
# Zones allow you to specify certain regions on earth (for now). 
#
# https://www.home-assistant.io/components/zone
#
name: Matt's Work
latitude: !secret zone_mswork_latitude
longitude: !secret zone_mswork_longitude
radius: 100
passive: false
icon: mdi:domain