---
#
# Template sensor to display the thermostat cool min temp
#
# https://www.home-assistant.io/components/sensor.template/
# 
platform: template
sensors:
  thermostat_cool_min_temp:
    friendly_name: "Thermostat Cool Minimum Temperature"
    device_class: "temperature"
    unit_of_measurement: "°F"
    value_template: >-
      {%- if state_attr('climate.2gig_technologies_ct101_thermostat_iris_cooling_1', 'min_temp') %}
          {{ state_attr('climate.2gig_technologies_ct101_thermostat_iris_cooling_1', 'min_temp') }}
      {% else %}
          Unknown
      {%- endif %}