---
#
# Template sensor to display the thermostat heating current temp
#
# https://www.home-assistant.io/components/sensor.template/
# 
platform: template
sensors:
  thermostat_heat_current_temperature:
    friendly_name: "Thermostat Heat Current Temperature"
    value_template: >-
      {%- if state_attr('climate.2gig_technologies_ct101_thermostat_iris_heating_1', 'current_temperature') %}
          {{ state_attr('climate.2gig_technologies_ct101_thermostat_iris_heating_1', 'current_temperature') }}
      {% else %}
          Unknown
      {%- endif %}