---
#
# Template sensor to display the thermostat heating operation mode
#
# https://www.home-assistant.io/components/sensor.template/
# 
platform: template
sensors:
  thermostat_heat_operation_mode_state:
    friendly_name: "Thermostat Heat Fan State"
    value_template: >-
      {%- if state_attr('climate.2gig_technologies_ct101_thermostat_iris_heating_1', 'operation_mode') %}
          {{ state_attr('climate.2gig_technologies_ct101_thermostat_iris_heating_1', 'operation_mode') }}
      {% else %}
          Unknown
      {%- endif %}