---
# This is actually just a bootstrap for my Lovelace configuration.

# It loads all resources for Lovelace dynamically from sub-folders
# inside the `lovelace/resources` directory.
#
# Views are actually include one by one, this to guarantee the order of
# the tabs of the view in the UI.
#
title: Home Control Panel
custom_header:
  compact_mode: true
views:
  - !include lovelace/views/general.yaml
  - !include lovelace/views/basement.yaml
  - !include lovelace/views/firstfloor.yaml
  - !include lovelace/views/secondfloor.yaml
  - !include lovelace/views/thirdfloor.yaml
  - !include lovelace/views/automations.yaml
  - !include lovelace/views/server.yaml