---
#
# switch booleans back to normal
#
id: Switch booleans to normal values
alias: Reset at night
initial_state: 'on'
trigger:
  - platform: time
    at: "23:00:00"
action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.movie_mode