---
# The darksky platform uses the Dark Sky web service as a source for
# meteorological data for your location.
#
# https://www.home-assistant.io/components/weather.darksky/
#
platform: darksky
api_key: !secret dark_sky_api
mode: daily
update_interval:
  minutes: 5