---
#
# notify when a door opens
#
id: Door Open
alias: Door Opened
initial_state: 'off'
trigger:
  - platform: state
    entity_id: 
      - binary_sensor.neo_coolcam_door_window_detector_sensor_2
      - binary_sensor.neo_coolcam_door_window_detector_sensor
    to: 'on'
action:
- service: script.sonos_say
  data_template:
    sonos_entity: livingroom_sonos
    volume: 0.5
    message: 'Welcome to our Home!  Please close the {{ trigger.to_state.name }} behind you.! '
