---
id: Automations
title: Automations
icon: mdi:settings
cards:
  - type: custom:monster-card
    card:
      type: entities
      title: "Automations"
    filter:
      include:
        - entity_id: automation.*
  - type: custom:monster-card
    card:
      type: entities
      title: "Scenes"
    filter:
      include:
        - entity_id: scene.*
  - type: custom:monster-card
    card:
      type: entities
      title: "Booleans"
    filter:
      include:
        - entity_id: input_boolean.*
  - type: custom:monster-card
    card:
      type: entities
      title: "Entities"
    filter:
      include:
        - entity_id: sensor.*