---
id: First Floor
title: First Floor
icon: mdi:sofa
cards:
  - type: custom:compact-custom-header
  - type: vertical-stack
    cards:
      - type: entities
        title: Lights
        entities:
          - type: custom:slider-entity-row
            entity: light.kohree2
            toggle: true
          - type: custom:slider-entity-row
            entity: light.kohree_1
            toggle: true
          - group.living_room
  - type: vertical-stack
    cards:
      - type: entities
        title: Outside Lights
        entities:
          - type: custom:slider-entity-row
            entity: light.sengled_e11_g13_030bbd4e_1
            toggle: true
          - type: custom:slider-entity-row
            entity: light.sengled_e11_g13_030ba3b9_1
            toggle: true
  - type: custom:monster-card
    card:
      type: entities
      title: "Doors"
    filter:
      include:
        - entity_id: binary_sensor.neo_coolcam_door_window_detector_sensor_2
        - entity_id: binary_sensor.neo_coolcam_door_window_detector_sensor
  - type: vertical-stack
    cards:
      - type: entities
        title: Media
        entities:
          - type: custom:mini-media-player
            entity: media_player.living_room_tv
          - type: custom:mini-media-player
            entity: media_player.livingroom_sonos
            tts:
              platform: 'google'
              volume: 0.75
            sonos: 
              show_group_count: true
              entities: !include sonosgroups.yaml
          - type: custom:mini-media-player
            entity: media_player.spare
            tts:
              platform: 'google'
              volume: 0.75
            sonos: 
              show_group_count: true
              entities: !include sonosgroups.yaml
