---
id: First Floor
title: First Floor
icon: mdi:sofa
cards:
  - type: vertical-stack
    cards:
      - type: entities
        title: Outside Lights
        entities:
          - type: custom:slider-entity-row
            entity: light.sengled_e11_g13_030bbd4e_1
            toggle: true
          - type: custom:slider-entity-row
            entity: light.sengled_e11_g13_030ba3b9_1
            toggle: true
  - type: custom:auto-entities
    card:
      type: entities
      title: "Plugs"
    filter:
      include:
        - entity_id: switch.ikea_of_sweden_tradfri_control_outlet_fe2d4470_1
    sort:
      method: name
  - type: custom:auto-entities
    card:
      type: entities
      title: "Doors"
    filter:
      include:
        - entity_id: binary_sensor.neo_coolcam_door_window_detector_sensor_2
        - entity_id: binary_sensor.neo_coolcam_door_window_detector_sensor
    sort:
      method: name
  - type: custom:mini-graph-card
    name: Temperature
    icon: mdi:home-thermometer
    hours_to_show: 168
    points_per_hour: 0.25
    entities:
      - entity: sensor.kitchen_temperature
        name: Kitchen
        show_state: true
      - entity: sensor.living_room_temp
        name: Living Room
        show_state: true
      - entity: sensor.radio_thermostat_company_of_america_ct101_thermostat_iris_temperature
        name: Thermostat
        show_state: true
  - type: vertical-stack
    cards:
      - type: entities
        title: Media
        entities:
          - type: custom:mini-media-player
            entity: media_player.master_bedroom_tv
          - type: custom:mini-media-player
            entity: media_player.livingroom_sonos
            tts:
              platform: 'google_translate'
              volume: 0.75
            sonos: 
              show_group_count: true
              entities: !include sonosgroups.yaml
