---
id: First Floor
title: First Floor
icon: mdi:sofa
cards:
  - type: custom:auto-entities
    card:
      type: entities
      title: "Fun Lights"
    filter:
      include:
        - entity_id: light.big_inifinity_mirror
    sort:
      method: name
  - type: vertical-stack
    cards:
      - type: entities
        title: Media
        entities:
          - type: custom:mini-media-player
            entity: media_player.vizio_tv
          - type: custom:mini-media-player
            entity: media_player.sunroom_tv
          - type: custom:mini-media-player
            entity: media_player.livingroom_sonos
            tts:
              platform: 'google_translate'
              volume: 0.75
            sonos: 
              show_group_count: true
              entities: !include sonosgroups.yaml
          - type: custom:mini-media-player
            entity: media_player.spare
            tts:
              platform: 'google_translate'
              volume: 0.75
            sonos: 
              show_group_count: true
              entities: !include sonosgroups.yaml
