---
id: General
title: General
icon: mdi:function
cards:
  - type: thermostat
    entity: climate.radio_thermostat_company_of_america_ct101_thermostat_iris_mode
    name: Thermostat
  - type: custom:mini-graph-card
    name: Temperature
    icon: mdi:home-thermometer
    hours_to_show: 168
    points_per_hour: 0.25
    entities:
     - entity: sensor.global_temperature
       name: Internal
       show_state: true
     - entity: sensor.dark_sky_temperature
       name: Dark Sky
       show_state: true
     - entity: sensor.openweathermap_temperature
       name: Open Weather Map
       show_state: true
     - entity: sensor.weatherbit_temperature
       name: Weatherbit
       show_state: true
  - type: custom:weather-card
    entity: weather.dark_sky
    icons: '/local/images/weather_icons/'
    name: Dark Sky
  - type: custom:weather-card
    entity: weather.openweathermap
    icons: '/local/images/weather_icons/'
    name: Open Weather
  - type: custom:weather-card
    entity: weather.weatherbit_lowell
    icons: '/local/images/weather_icons/'
    name: Weatherbit.io
  - type: vertical-stack
    cards:
      - type: entities
        title: People
        entities:
          - person.erin
          - person.kedar
          - person.matt
  - type: "custom:birthday-card"
    title: "Birthdays"
    numberofdays: 365