---
id: General
title: General
icon: mdi:function
cards:
  - type: custom:dual-thermostat
    name: Thermostat
    entities:
      - entity: climate.2gig_technologies_ct101_thermostat_iris_cooling_1
        type: cool
      - entity: climate.2gig_technologies_ct101_thermostat_iris_heating_1
        type: heat
    fan_control: true
    min_slider: 50
    max_slider: 95
  - type: custom:mini-graph-card
    name: Temperature
    icon: mdi:home-thermometer
    hours_to_show: 168
    points_per_hour: 0.25
    entities:
     - entity: sensor.global_temperature
       name: Internal
       show_state: true
     - entity: sensor.dark_sky_temperature
       name: External
       show_state: true
  - type: custom:weather-card
    entity: weather.dark_sky
    icons: '/local/lovelace/cards/weather-card/icons/'
  - type: vertical-stack
    cards:
      - type: entities
        title: People
        entities:
          - person.erin
          - person.kedar
          - person.matt
  - type: "custom:day-countdown"
    date: "August 16 2019"
    title: "Cruise Vacation"
  - type: "custom:birthday-card"
    title: "Birthdays"
    numberofdays: 365