---
id: General
title: General
icon: mdi:function
cards:
  - type: thermostat
    entity: climate.2gig_technologies_ct101_thermostat_iris_cooling_1
  - type: thermostat
    entity: climate.2gig_technologies_ct101_thermostat_iris_heating_1
  - type: custom:weather-card
    entity: weather.dark_sky
  - type: vertical-stack
    cards:
      - type: entities
        title: Devices
        entities:
          - device_tracker.owntracks_erin
          - device_tracker.owntracks_kedar
          - device_tracker.owntracks_matt
  - type: "custom:day-countdown"
    date: "Jan 28 2019"
    title: "Kedar's Birthday"