---
id: Second Floor
title: Second Floor
icon: mdi:bed-empty
cards:
  - type: vertical-stack
    cards:
      - type: entities
        title: Lights
        entities:
          - light.master_bedroom_extra_room
          - light.kids_night_light
  - type: custom:mini-graph-card
    name: Temperature
    icon: mdi:home-thermometer
    hours_to_show: 168
    points_per_hour: 0.25
    entities:
     - entity: sensor.master_bedroom_temp_humidity_air_temperature
       name: Master Bedroom Temperature
       show_state: true
  - type: vertical-stack
    cards:
      - type: entities
        title: Media
        entities:
          - type: custom:mini-media-player
            entity: media_player.erins_room_tv
          - type: custom:mini-media-player
            entity: media_player.master_bedroom_tv
          - type: custom:mini-media-player
            entity: media_player.adult_sonos
            tts:
              platform: 'google_translate'
              volume: 0.75
            sonos: 
              show_group_count: true
              entities: !include sonosgroups.yaml
          - type: custom:mini-media-player
            entity: media_player.kids_bedroom
            tts:
              platform: 'google_translate'
              volume: 0.75
            sonos: 
              show_group_count: true
              entities: !include sonosgroups.yaml
  - type: vertical-stack
    cards:
      - type: entities
        title: Fun Lights
        entities:
          - light.henry_infinity_mirror
          - light.david_infinity_mirror
