---
id: Second Floor
title: Second Floor
icon: mdi:bed-empty
cards:
  - type: vertical-stack
    cards:
      - type: entities
        title: Lights
        entities:
          - type: custom:slider-entity-row
            entity: light.master_bedroom
            name: Bedroom
            toggle: true
          - group.master_bedroom_closet
          - group.master_bedroom_night_lights
          - scene.laying_in_bed
          - switch.henrys_desklight
  - type: vertical-stack
    cards:
      - type: entities
        title: Side Lights
        entities:
          - light.kedar_night_light
          - light.matt_night_light
  - type: vertical-stack
    cards:
      - type: entities
        title: Fans
        entities:
          - switch.window_fans_computer
          - switch.window_fan_bed
  - type: custom:mini-graph-card
    name: Temperature
    icon: mdi:home-thermometer
    hours_to_show: 168
    points_per_hour: 0.25
    entities:
      - entity: sensor.master_bedroom_temperature
        name: Master Bedroom
        show_state: true
      - entity: sensor.master_bath_temperature
        name: Master Bathroom
        show_state: true
      - entity: sensor.master_bedroom_closet_temp
        name: Master Bedroom Closet
        show_state: true
  - type: vertical-stack
    cards:
      - type: entities
        title: Media
        entities:
          - type: custom:mini-media-player
            entity: media_player.living_room_tv
          - type: custom:mini-media-player
            entity: media_player.adult_sonos
            tts:
              platform: 'google_translate'
              volume: 0.75
            sonos: 
              show_group_count: true
              entities: !include sonosgroups.yaml
