---
id: Second Floor
title: Second Floor
icon: mdi:bed-empty
cards:
  - type: vertical-stack
    cards:
      - type: entities
        title: Lights
        entities:
          - type: custom:slider-entity-row
            entity: light.master_bedroom
            name: Bedroom
            toggle: true
          - group.master_bedroom_closet
          - group.master_bedroom_night_lights
          - scene.laying_in_bed
  - type: vertical-stack
    cards:
      - type: entities
        title: Devices
        entities:
          - light.kedar_s_night_light
          - light.matt_s_night_light
          - switch.master_bedroom_window_fan
          - switch.fan_matts_side
          - switch.henrys_computer
  - type: vertical-stack
    cards:
      - type: entities
        title: Media
        entities:
          - type: custom:mini-media-player
            entity: media_player.living_room_tv
          - type: custom:mini-media-player
            entity: media_player.adult_sonos
            tts:
              platform: 'google_translate'
              volume: 0.75
            sonos: 
              show_group_count: true
              entities: !include sonosgroups.yaml
