---
id: Second Floor
title: Second Floor
icon: mdi:bed-empty
cards:
  - type: vertical-stack
    cards:
      - type: entities
        title: Lights
        entities:
          - type: custom:slider-entity-row
            entity: light.master_bedroom
            name: Bedroom
            toggle: true
          - type: custom:slider-entity-row
            entity: light.sengled_e11_g13_030ba25e_1
            name: Closet 1
            toggle: true
          - type: custom:slider-entity-row
            entity: light.sengled_e11_g13_030bbabf_1
            name: Closet 2
            toggle: true
          - scene.laying_in_bed
  - type: vertical-stack
    cards:
      - type: entities
        title: Devices
        entities:
          - switch.gosund_1
          - switch.gosund_2
  - type: vertical-stack
    cards:
      - type: entities
        title: Media
        entities:
          - type: custom:mini-media-player
            entity: media_player.master_bedroom_tv
          - type: custom:mini-media-player
            entity: media_player.adult_sonos
            sonos: !include sonosgroups.yaml
