---
id: Server
title: Server
icon: mdi:nas
visible:
  - user: 2e85aebd0a9c436c8567c5435f0d0df8
cards:
  - type: custom:auto-entities
    card:
      type: entities
      title: "Sensors"
    filter:
      include:
        - entity_id: sensor.potential_breaking_changes
    sort:
      method: name