---
id: Server
title: Server
icon: mdi:nas
cards:
  - type: vertical-stack
    cards:
      - type: sensor
        entity: sensor.tautulli
        name: tautulli
      - type: sensor
        entity: sensor.unraid_qbittorrent_down_speed
        name: qBittorrent Down
      - type: sensor
        entity: sensor.unraid_qbittorrent_up_speed
        name: qBittorrent Up
      - type: sensor
        entity: sensor.unraid_qbittorrent_down_speed
        name: qBittorrent Down
      - type: sensor
        entity: sensor.unraid_transmission_down_speed
        name: Transmission Up
      - type: sensor
        entity: sensor.unraid_transmission_up_speed
        name: Transmission Down
  - type: custom:tracker-card
    title: "Custom Components"
    trackers:
      - sensor.custom_card_tracker
      - sensor.custom_component_tracker