---
id: Server
title: Server
icon: mdi:nas
cards:
  - type: custom:auto-entities
    card:
      type: entities
      title: "Sensors"
    filter:
      include:
        - entity_id: sensor.potential_breaking_changes
  - type: custom:auto-entities
    card:
      type: entities
      title: "Sensors"
    filter:
      include:
        - entity_id: "switch.ha_dockermon_*"