---
id: Third Floor
title: Third Floor
icon: mdi:briefcase
cards:
  - type: vertical-stack
    cards:
      - type: entities
        title: Lights
        entities:
          - light.matt_office_light
