---
id: Third Floor
title: Third Floor
icon: mdi:bed-empty
cards:
  - type: vertical-stack
    cards:
      - type: entities
        title: Lights
        entities:
          - type: custom:slider-entity-row
            entity: light.kids_bedroom
            toggle: true
  - type: vertical-stack
    cards:
      - type: entities
        title: Media
        entities:
          - type: custom:mini-media-player
            entity: media_player.erins_room_tv
            show_tts: false
            show_source: true
            show_progress: false
            hide_controls: false
            power_color: true
            more_info: false
            volume_stateless: true
          - type: custom:mini-media-player
            entity: media_player.kids_bedroom
            show_tts: true
            show_source: true
            show_progress: false
            hide_controls: false
            power_color: true
            more_info: false
            volume_stateless: true
