---
id: Third Floor
title: Third Floor
icon: mdi:briefcase
cards:
  - type: custom:auto-entities
    card:
      type: entities
      title: "Fun Lights"
    filter:
      include:
        - entity_id: light.big_inifinity_mirror
        - entity_id: switch.office_christmas_tree
    sort:
      method: name
  - type: vertical-stack
    cards:
      - type: entities
        title: Lights
        entities:
          - light.matt_office_light
  - type: custom:mini-graph-card
    name: Temperature
    icon: mdi:home-thermometer
    hours_to_show: 168
    points_per_hour: 0.25
    entities:
     - entity: sensor.office_temp_humidity_sensor_temperature
       name: Office Temperature
       show_state: true