---
id: Third Floor
title: Third Floor
icon: mdi:bed-empty
cards:
  - type: vertical-stack
    cards:
      - type: entities
        title: Lights
        entities:
          - type: custom:slider-entity-row
            entity: light.kids_bedroom
            toggle: true
  - type: vertical-stack
    cards:
      - type: entities
        title: Media
        entities:
          - type: custom:mini-media-player
            entity: media_player.erins_room_tv
          - type: custom:mini-media-player
            entity: media_player.kids_bedroom
            sonos: 
              show_group_count:true
              entities:
                !include sonosgroups.yaml
