---
#
# min_max sensor to display the average temp from various sensors
#
# https://www.home-assistant.io/integrations/min_max/
# 
platform: min_max
entity_ids:
  - sensor.dark_sky_overnight_low_temperature_0d
  - sensor.openweathermap_forecast_temperature_low
  - sensor.weatherbit_forecast_low_temperature
  - sensor.climacell_forecast_low_temperature
  - sensor.pirateweather_overnight_low_temperature_0d
name: "Average Weather Low Temperature"
type: median
