---
# Android TV
#
# https://www.home-assistant.io/integrations/androidtv/
#
# The androidtv platform allows you to control an 
# Android TV device or Amazon Fire TV device.
platform: androidtv 
name: Fire TV
host: !secret fire_tv_ip