---
# The Plex media player
#
# https://www.home-assistant.io/components/media_player.plex/
#
platform: plex
entity_namespace: 'plex'
include_non_clients: false
scan_interval: 5
use_custom_entity_ids: true
use_episode_art: true
remove_unavailable_clients: true
client_remove_interval: 600