---
#
# The google_translate text-to-speech platform uses unofficial
# Google Translate Text-to-Speech engine to read a text with natural sounding voices.
#
# https://www.home-assistant.io/components/google_translate/
#
platform: google_translate
language: 'en'
