---
#
# Template sensors to display the MA Covid cases
#
# https://www.home-assistant.io/components/sensor.template/
# 
platform: template
sensors:
  covid_positive_state:
    friendly_name: 'positive covid ma'
    value_template: '{{ states.sensor.statewide_covid_stats.attributes["positive"] }}'
  covid_negative_state:
    friendly_name: 'negative Covid ma'
    value_template: '{{ states.sensor.statewide_covid_stats.attributes["negative"] }}'
  covid_pending_state:
    friendly_name: 'pending Covid ma'
    value_template: '{{ states.sensor.statewide_covid_stats.attributes["pending"] }}'
  covid_hospitalized_state:
    friendly_name: 'hospitalized Covid ma'
    value_template: '{{ states.sensor.statewide_covid_stats.attributes["hospitalized"] }}'
  covid_death_state:
    friendly_name: 'death Covid ma'
    value_template: '{{ states.sensor.statewide_covid_stats.attributes["death"] }}'
  covid_total_state:
    friendly_name: 'total Covid ma'
    value_template: '{{ states.sensor.statewide_covid_stats.attributes["total"] }}'
  covid_update_state:
    friendly_name: 'last update Covid ma'
    value_template: '{{ states.sensor.statewide_covid_stats.attributes["lastUpdateEt"] }}'