---
#
# Group of everything
#
all lights custom:
    entities:
      - light.kids_bedroom
      - light.master_bedroom
#       Master Bedroom Closet
      - light.sengled_e11_g13_030ba25e_1
      - light.sengled_e11_g13_030bbabf_1
#      These switches control lights normally
      - switch.kedar_night_light
      - switch.matts_night_light