---
#
# Group of everything
#
all lights custom:
    control: hidden
    entities:
      - light.kids_bedroom
      - light.living_room
      - light.master_bedroom
      - light.sengled_e11_g13_030ba25e_1
      - light.sengled_e11_g13_030bbabf_1
      - switch.kedar_night_light
      - switch.master_bedroom_lamp