---
#
# MQTT virtual light from smartthings
#
platform: mqtt
name: "Kids Bedroom"
unique_id: "Kids Bedroom"
state_topic: "smartthings/Kids Room/switch/state"
command_topic: "smartthings/Kids Room/switch/cmd"
brightness_state_topic: "smartthings/Kids Room/level/state"
brightness_command_topic: "smartthings/Kids Room/level/cmd"
brightness_scale: 100
payload_on: "on"
payload_off: "off"
retain: true