---
#
# Template sensor to display the daily climacell temp
#
# https://www.home-assistant.io/components/sensor.template/
# 
platform: template
sensors:
  climacell_forecast_low_temperature:
    friendly_name: "Climacell Forecast Low Temperature"
    unit_of_measurement: "°F"
    value_template: >-
      {{ state_attr('weather.climacell_daily', 'forecast')[0].templow }}