---
#
# Template sensor to display the average temp from various sensors
#
# https://www.home-assistant.io/components/sensor.template/
# 
platform: template
sensors:
  global_temperature:
    friendly_name: "Global Temperature"
    unit_of_measurement: "°F"
    value_template: >-
      {{ ((states('sensor.master_bedroom_closet_motion_sensor_temp')|int)+ (states('sensor.living_room_motion_sensor_temp')|int) + (states('sensor.2gig_technologies_ct101_thermostat_iris_temperature')|int) + (states('sensor.2gig_technologies_ct101_thermostat_iris_temperature_2')|int)+ (states('sensor.zooz_zse40_4in1_sensor_temperature')|int)+ (states('sensor.visonic_mct_340_e_0b3e1c50_1_1026')|int))/6 }}
