---
#
# Template sensor to display the average temp from various sensors
#
# https://www.home-assistant.io/components/sensor.template/
# 
platform: template
sensors:
  global_temperature:
    friendly_name: "Global Temperature"
    unit_of_measurement: "°F"
    value_template: >-
      {{ ((states('sensor.living_room_temp')|int) + (states('sensor.master_bedroom_closet_temp')|int) + (states('sensor.thermostat_air_temperature')|int) + (states('sensor.kids_bedroom_sensor_air_temperature')|int) + (states('sensor.third_floor_landing_temperature')|int) + (states('sensor.erin_s_room_temperature')|int) + (states('sensor.master_bath_temperature')|int) + (states('sensor.master_bedroom_temperature')|int))/8 }}