---
#
# Template sensor to display the thermostat heat min temp
#
# https://www.home-assistant.io/components/sensor.template/
# 
platform: template
sensors:
  thermostat_heat_min_temp:
    friendly_name: "Thermostat Heat Minimum Temperature"
    value_template: >-
      {%- if state_attr('climate.2gig_technologies_ct101_thermostat_iris_heating_1', 'min_temp') %}
          {{ state_attr('climate.2gig_technologies_ct101_thermostat_iris_heating_1', 'min_temp') }}
      {% else %}
          Unknown
      {%- endif %}