---
#
# Template sensor to display the thermostat cool fan state
#
# https://www.home-assistant.io/components/sensor.template/
# 
platform: template
sensors:
  thermostat_cool_fan_state:
    friendly_name: "Thermostat Cool Fan State"
    value_template: >-
      {%- if state_attr('climate.2gig_technologies_ct101_thermostat_iris_cooling_1', 'fan_state') %}
          {{ state_attr('climate.2gig_technologies_ct101_thermostat_iris_cooling_1', 'fan_state') }}
      {% else %}
          Unknown
      {%- endif %}