---
#
# Template sensor to display the thermostat cool temp
#
# https://www.home-assistant.io/components/sensor.template/
# 
platform: template
sensors:
  thermostat_cool_temperature:
    friendly_name: "Thermostat Cool Temperature"
    value_template: >-
      {%- if state_attr('climate.2gig_technologies_ct101_thermostat_iris_cooling_1', 'temperature') %}
          {{ state_attr('climate.2gig_technologies_ct101_thermostat_iris_cooling_1', 'temperature') }}
      {% else %}
          Unknown
      {%- endif %}