---
#
# Template sensor to display the daily weatherbit temp
#
# https://www.home-assistant.io/components/sensor.template/
# 
platform: template
sensors:
  weatherbit_forecast_high_temperature:
    friendly_name: "Weatherbit Forecast High Temperature"
    unit_of_measurement: "°F"
    value_template: >-
      {{ state_attr('sensor.weatherbit_forecast_day_1_2', 'temperature') }}